### ISSUE TITLE
'byte' does not name a type

### ISSUE THREAD

**Issue by kaptk2** [ekbduffy/spark_websockets#12]
Veryfing code using this library in Particle Build fails with this error:
```
Spark-Websockets/Spark-Websockets.h:72:3: error: 'byte' does not name a type
   byte _opCode

Trying to compile the example app inside of the web ide and this error happens

**Comment by tripzero** [comment]
looks like this fix needs to be updated (reimported) on the webIDE

**Comment by ekbduffy** [comment]
Hello, try it. I've reimported ,but not tested. Haven't time for this, and doesn't using webide
