### ISSUE TITLE
Error in the GET request

### ISSUE THREAD

**Issue by jackbell16** [ekbduffy/spark_websockets#17]
Hi,
it seems there is a problem with the GET request. My websocket server has the following URI:
ws://192.168.10.150/ExampleWebSocket/example.

When I put the code: client.connect("192.168.10.156",8080,"/ws","/ExampleWebSocket/example");
The GET request sniffed with Wireshark has GET / HTTP1.1 and not GET /ExampleWebSocket/example HTTP1.1 

Can you fix it?

**Comment by ekbduffy** [comment]
This client have really little number of settings. I will not modify it in near future, because i'm not working with Spark board anymore. So you can modify it by yourself:
String WebSocketClientStringTable in .h file can be changed and also you would change SendHandshake function in .c file.
